#!/bin/bash

{
    ext=${1##*.}
    f=${1%.$ext}
    printf '[spoiler]\n'
    for i in html css js; do
        [[ -e $f.$i ]] || continue
        printf '```%s\n' "$i"
        cat $f.$i
        printf '```\n'
    done
    printf '[/spoiler]\n'
} | xclip -i

