# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62\x61nk_account.proto\x12\x07\x61\x63\x63ount\"\x1d\n\x0bOpenRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\"\x1e\n\x0cOpenResponse\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\"\x0e\n\x0c\x43loseRequest\"\x1f\n\rCloseResponse\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\"\x10\n\x0e\x42\x61lanceRequest\"!\n\x0f\x42\x61lanceResponse\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\" \n\x0e\x44\x65positRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\"!\n\x0f\x44\x65positResponse\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\x32\xfa\x01\n\x04\x42\x61nk\x12\x35\n\x04Open\x12\x14.account.OpenRequest\x1a\x15.account.OpenResponse\"\x00\x12\x38\n\x05\x43lose\x12\x15.account.CloseRequest\x1a\x16.account.CloseResponse\"\x00\x12\x41\n\nGetBalance\x12\x17.account.BalanceRequest\x1a\x18.account.BalanceResponse\"\x00\x12>\n\x07\x44\x65posit\x12\x17.account.DepositRequest\x1a\x18.account.DepositResponse\"\x00\x42\x18Z\x16\x65xample.com/bank/protob\x06proto3')



_OPENREQUEST = DESCRIPTOR.message_types_by_name['OpenRequest']
_OPENRESPONSE = DESCRIPTOR.message_types_by_name['OpenResponse']
_CLOSEREQUEST = DESCRIPTOR.message_types_by_name['CloseRequest']
_CLOSERESPONSE = DESCRIPTOR.message_types_by_name['CloseResponse']
_BALANCEREQUEST = DESCRIPTOR.message_types_by_name['BalanceRequest']
_BALANCERESPONSE = DESCRIPTOR.message_types_by_name['BalanceResponse']
_DEPOSITREQUEST = DESCRIPTOR.message_types_by_name['DepositRequest']
_DEPOSITRESPONSE = DESCRIPTOR.message_types_by_name['DepositResponse']
OpenRequest = _reflection.GeneratedProtocolMessageType('OpenRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENREQUEST,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.OpenRequest)
  })
_sym_db.RegisterMessage(OpenRequest)

OpenResponse = _reflection.GeneratedProtocolMessageType('OpenResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPENRESPONSE,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.OpenResponse)
  })
_sym_db.RegisterMessage(OpenResponse)

CloseRequest = _reflection.GeneratedProtocolMessageType('CloseRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEREQUEST,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.CloseRequest)
  })
_sym_db.RegisterMessage(CloseRequest)

CloseResponse = _reflection.GeneratedProtocolMessageType('CloseResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOSERESPONSE,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.CloseResponse)
  })
_sym_db.RegisterMessage(CloseResponse)

BalanceRequest = _reflection.GeneratedProtocolMessageType('BalanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _BALANCEREQUEST,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.BalanceRequest)
  })
_sym_db.RegisterMessage(BalanceRequest)

BalanceResponse = _reflection.GeneratedProtocolMessageType('BalanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _BALANCERESPONSE,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.BalanceResponse)
  })
_sym_db.RegisterMessage(BalanceResponse)

DepositRequest = _reflection.GeneratedProtocolMessageType('DepositRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPOSITREQUEST,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.DepositRequest)
  })
_sym_db.RegisterMessage(DepositRequest)

DepositResponse = _reflection.GeneratedProtocolMessageType('DepositResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEPOSITRESPONSE,
  '__module__' : 'bank_account_pb2'
  # @@protoc_insertion_point(class_scope:account.DepositResponse)
  })
_sym_db.RegisterMessage(DepositResponse)

_BANK = DESCRIPTOR.services_by_name['Bank']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026example.com/bank/proto'
  _OPENREQUEST._serialized_start=31
  _OPENREQUEST._serialized_end=60
  _OPENRESPONSE._serialized_start=62
  _OPENRESPONSE._serialized_end=92
  _CLOSEREQUEST._serialized_start=94
  _CLOSEREQUEST._serialized_end=108
  _CLOSERESPONSE._serialized_start=110
  _CLOSERESPONSE._serialized_end=141
  _BALANCEREQUEST._serialized_start=143
  _BALANCEREQUEST._serialized_end=159
  _BALANCERESPONSE._serialized_start=161
  _BALANCERESPONSE._serialized_end=194
  _DEPOSITREQUEST._serialized_start=196
  _DEPOSITREQUEST._serialized_end=228
  _DEPOSITRESPONSE._serialized_start=230
  _DEPOSITRESPONSE._serialized_end=263
  _BANK._serialized_start=266
  _BANK._serialized_end=516
# @@protoc_insertion_point(module_scope)
